account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .forms import PwdResetConfirmForm, PwdResetForm, UserLoginForm

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html',
                                                form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/account/login/'), name='logout'),
    path('register/', views.account_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>', views.account_activate, name='activate'),
    # Reset password
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="user/password_reset_form.html",
                                                                 success_url='password_reset_email_confirm',
                                                                 email_template_name='user/password_reset_email.html',
                                                                 form_class=PwdResetForm), name='pwdreset'),
    path('password_reset_confirm/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(template_name='user/password_reset_confirm.html',
                                                     success_url='/account/password_reset_complete/',
                                                     form_class=PwdResetConfirmForm),
         name="password_reset_confirm"),
    path('password_reset/password_reset_email_confirm/',
         TemplateView.as_view(template_name="user/reset_status.html"), name='password_reset_done'),
    path('password_reset_complete/',
         TemplateView.as_view(template_name="user/reset_status.html"), name='password_reset_complete'),
    # User dashboard
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/edit/', views.edit_details, name='edit_details'),
    path('profile/delete-user/', views.delete_user, name='delete_user'),
    path('profile/delete-confirm/', TemplateView.as_view(template_name='user/delete_confirm.html'),
         name='delete_confirmation'),
    path('addresses/', views.view_address, name='addresses'),
    path('add-address/', views.add_address, name='add_address'),
    path('addresses/edit/<slug:id>/', views.edit_address, name='edit_address'),
    path('addresses/delete/<slug:id>/', views.delete_address, name='delete_address'),
    path('addresses/set-default/<slug:id>/', views.set_default, name='set_default'),
    # Wish list
    path('wishlist/', views.wishlist, name='wishlist'),
    path('withlist/add-to-wishlist/<int:id>/', views.add_to_wishlist, name="add_to_wishlist"),
]

core/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('orders/', include('order.urls', namespace='orders')),
    path('__debug__', include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

account/forms.py
from django import forms
from django.contrib.auth.forms import (AuthenticationForm, PasswordResetForm,
                                       SetPasswordForm)

from .models import Address, Customer


class UserAddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ["full_name", "phone_number", "address_line_1", "address_line_2", "town_city", "postcode"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["full_name"].widget.attrs.update(
            {"class": "form-control mb-2 account-form", "placeholder": "Full Name"}
        )
        self.fields["phone_number"].widget.attrs.update(
            {"class": "form-control mb-2 account-form", "placeholder": "phone number"}
        )
        self.fields["address_line_1"].widget.attrs.update(
            {"class": "form-control mb-2 account-form", "placeholder": "Address line 1"}
        )
        self.fields["address_line_2"].widget.attrs.update(
            {"class": "form-control mb-2 account-form", "placeholder": "Address line 2"}
        )
        self.fields["town_city"].widget.attrs.update(
            {"class": "form-control mb-2 account-form", "placeholder": "Town city"}
        )
        self.fields["postcode"].widget.attrs.update(
            {"class": "form-control mb-2 account-form", "placeholder": "Post Code"}
        )


class UserLoginForm(AuthenticationForm):

    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control mb-3', 'placeholder': 'Username', 'id': 'login-username'}))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Password',
            'id': 'login-pwd',
        }
    ))


class RegistrationForm(forms.ModelForm):
    user_name = forms.CharField(label='Enter Username', min_length=4, max_length=50, help_text='Required')
    email = forms.EmailField(max_length=100, help_text='Required',
                             error_messages={'required': 'Sorry, you will need an email'})
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = Customer
        fields = ('user_name', 'email',)

    def clean_username(self):
        user_name = self.cleaned_data['user_name'].lower()
        r = Customer.objects.filter(user_name=user_name)
        if r.count():
            raise forms.ValidationError('Username already exists')
        return user_name

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords do not match.')
        return cd['password2']

    def clean_email(self):
        email = self.cleaned_data['email']
        if Customer.objects.filter(email=email).exists():
            raise forms.ValidationError(
                'Please use another email, that is already taken')
        return email

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user_name'].widget.attrs.update({'class': 'form-control mb-3', 'placeholder': 'Username'})
        self.fields['email'].widget.attrs.update({'class': 'form-control mb-3', 'placeholder': 'Email'})
        self.fields['password'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'Password', 'name': 'email'})
        self.fields['password2'].widget.attrs.update({'class': 'form-control mb-3', 'placeholder': 'Repeat Password'})


class PwdResetForm(PasswordResetForm):

    email = forms.EmailField(max_length=254, widget=forms.TextInput(
        attrs={'class': 'form-control mb-3', 'placeholder': 'Email', 'id': 'form-email'}))

    def clean_email(self):
        email = self.cleaned_data['email']
        u = Customer.objects.filter(email=email)
        if not u:
            raise forms.ValidationError(
                'Unfortunatley we can not find that email address')
        return email


class PwdResetConfirmForm(SetPasswordForm):
    new_password1 = forms.CharField(
        label='New password', widget=forms.PasswordInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'New Password', 'id': 'form-newpass'}))
    new_password2 = forms.CharField(
        label='Repeat password', widget=forms.PasswordInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'New Password', 'id': 'form-new-pass2'}))


class UserEditForm(forms.ModelForm):

    email = forms.EmailField(
        label='Account email (can not be changed)', max_length=200, widget=forms.TextInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'email', 'id': 'form-email', 'readonly': 'readonly'}))

    user_name = forms.CharField(
        label='Firstname', min_length=4, max_length=50, widget=forms.TextInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'Username',
                   'id': 'form-firstname', 'readonly': 'readonly'}))

    first_name = forms.CharField(
        label='Username', min_length=4, max_length=50, widget=forms.TextInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'Firstname', 'id': 'form-lastname'}))

    class Meta:
        model = Customer
        fields = ('email', 'user_name', 'first_name',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user_name'].required = True
        self.fields['email'].required = True

account/views.py
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode

from order.views import user_orders
from store.models import Product

from .forms import RegistrationForm, UserAddressForm, UserEditForm
from .models import Address, Customer
from .token import account_activation_token


@login_required
def wishlist(request):
    products = Product.objects.filter(users_wishlist=request.user.id)
    return render(request, 'dashboard/user_wish_list.html', {'wishlist': products})


@login_required
def add_to_wishlist(request, id):
    product = get_object_or_404(Product, pk=id)
    if product.users_wishlist.filter(id=request.user.id).exists():
        product.users_wishlist.remove(request.user)
        messages.success(request, product.title + " has been removed from your WishList.")
    else:
        product.users_wishlist.add(request.user)
        messages.success(request, "Added " + product.title + " to your WishList.")
    return HttpResponseRedirect(request.META["HTTP_REFERER"])


@login_required
def dashboard(request):
    orders = user_orders(request)
    return render(request, 'dashboard/dashboard.html', {'orders': orders})


@login_required
def edit_details(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.POST)

        if user_form.is_valid():
            user_form.save()
    else:
        user_form = UserEditForm(instance=request.user)

    return render(request, 'user/edit_details.html', {'user_form': user_form})


@login_required
def delete_user(request):
    user = Customer.objects.get(user_name=request.user)
    user.is_active = False
    user.save()
    logout(request)
    return redirect('account:delete_confirmation')


def account_register(request):
    if request.user.is_authenticated:
        return redirect('/')

    if request.method == 'POST':
        registerForm = RegistrationForm(request.POST)
        if registerForm.is_valid():
            user = registerForm.save(commit=False)
            cd = registerForm.cleaned_data
            user.email = cd['email']
            user.set_password(cd['password'])
            user.is_active = False
            user.save()
            # Setup email
            current_site = get_current_site(request)
            subject = 'Activate your Account'
            message = render_to_string('registration/account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            user.email_user(subject=subject, message=message)
            return HttpResponse('registered succesfully and activation sent')
    else:
        registerForm = RegistrationForm()
    return render(request, 'registration/register.html', {'form': registerForm})


def account_activate(request, uidb64, token):
    user = None
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = Customer.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, user.DoesNotExist):
        pass

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        return redirect('account:dashboard')
    else:
        return render(request, 'registration/activation_invalid.html')


# Addresses

@login_required
def view_address(request):
    addresses = Address.objects.filter(customer=request.user)
    return render(request, 'dashboard/addresses.html', {'addresses': addresses})


@login_required
def add_address(request):
    if request.method == 'POST':
        form = UserAddressForm(data=request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.customer = request.user
            form.save()
            return HttpResponseRedirect(reverse('account:addresses'))
    else:
        form = UserAddressForm()
    return render(request, 'dashboard/edit_addresses.html', {"form": form})


@login_required
def edit_address(request, id):
    if request.method == 'POST':
        address = Address.objects.get(pk=id, customer=request.user)
        form = UserAddressForm(data=request.POST, instance=address)
        if form.is_valid():
            form.save()
            HttpResponseRedirect(reverse('account:addresses'))
    else:
        address = Address.objects.get(pk=id, customer=request.user)
        form = UserAddressForm(instance=address)
    return render(request, 'dashboard/edit_addresses.html', {"form": form})


@login_required
def delete_address(request, id):
    address = Address.objects.get(pk=id, customer=request.user)
    address.delete()
    return redirect(reverse("account:addresses"))


@login_required
def set_default(request, id):
    """ set default address """
    Address.objects.filter(customer=request.user, default=True).update(default=False)
    Address.objects.filter(pk=id, customer=request.user).update(default=True)
    return redirect("account:addresses")

account/templates/user/delete_confirm.html
{% extends "base.html" %}
{% block title %}Log-in{% endblock %}
{% block content %}

<style>
    .account-form input {
        border: 2px solid #ccc;
        height: calc(2em + .75rem + 2px);
    }

    .account-form input:focus {
        border-color: #1497ff;
        box-shadow: none;
    }
</style>

<div class="container-fluid">
    <div class="row no-gutter">
        <div class="col-md-12">
            <div class="login d-flex align-items-center py-5">
                <div class="container">
                    <div class="row">
                        <div class="col-12 col-lg-6 mx-auto">
                            <div class="p-4">
                                <h3 class="mb-4">Account deleted</h3>
                                <p>Thank you</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

account/templates/user/edit_details.html
{% extends "base.html" %}
{% block title %}Edit Profile{% endblock %}
{% block content %}

<style>
    .account-form input {
        border: 2px solid #ccc;
        height: calc(2em + .75rem + 2px);
    }

    .account-form input:focus {
        border-color: #1497ff;
        box-shadow: none;
    }
</style>

<div class="container-fluid">
    <div class="row no-gutter">
        <div class="col-md-12">
            <div class="login d-flex align-items-center py-5">
                <div class="container">
                    <div class="row">
                        <div class="col-12 col-lg-7  mx-auto">

                 <form class="account-form px-4 pt-4" method="post" enctype="multipart/form-data">

                    {% if user_form.is_valid and profile_form.is_valid  %}
                    <div class="alert alert-primary" role="alert">
                        Details successfully updated!
                    </div>
                    <p class="small text-center pt-0">
                        <a href="{% url "account:dashboard" %}">Back to Dashboard</a>
                    </p>
                    {%else%}
                    <h3>Change your details</h3>
                    <p>You can edit your account using the following form:</p>
                    {% endif %}

                    {% if form.errors %}
                    <div class="alert alert-primary" role="alert">
                        Error: Please try again!
                    </div>
                    {% endif %}

                    {% csrf_token %}
                    <label class="small font-weight-bold">{{ user_form.email.label}}</label>
                    {{ user_form.email }}
                    <label class="small font-weight-bold">{{ user_form.first_name.label}}</label>
                    {{ user_form.first_name }}



                    <button class="btn btn-primary btn-block py-2 mb-4 mt-5 fw-bold w-100" type="submit"
                        value="Save changes">Save Changes</button>
                    <hr class="mb-3">
                </form>
                     <form class="account-form px-4" action="{% url "account:delete_user" %}" method="post">
                        {% csrf_token %}
                        <p class=" h3 pt-4 font-weight-bold">Delete Account</p>
                        <p>Are you sure you want to delete your account?</p>
                        <button type="submit" role="button"
                            class="btn btn-danger btn-block py-2 mb-4 mt-5 fw-bold w-100">Delete</button>
                    </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

account/templates/user/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}Log-in{% endblock %}
{% block content %}

{% if request.user.is_authenticated %}
<script>
    window.location.href = '{% url "account:dashboard" %}';
</script>
{% endif %}

<style>
    .login,
    .image {
        min-height: 100vh;
    }

    .bg-image {
        background-image: url('https://picsum.photos/id/433/1080');
        background-size: cover;
        background-position: center center;
    }

    .container-fluid {
        max-width: 100%;
    }

    body {
        margin-bottom: 0px;
    }

    .account-form input {
        border: 2px solid #ccc;
        height: calc(2em + .75rem + 2px);
    }

    .account-form input:focus {
        border-color: #1497ff;
        box-shadow: inset 0 0px 0px rgba(0, 0, 0, 0.075), 0 0 0px rgba(255, 0, 0, 0.6);
    }
</style>


<div class="container-fluid">
    <div class="row no-gutter">
        <div class="col-md-6 bg-light">
            <div class="login d-flex align-items-center py-5">
                <div class="container">
                    <div class="row">
                        <div class="col-12 col-md-12 mx-auto">

                            <form class="login-form p-4 rounded" method="post">
                                {% csrf_token %}
                                <h1 class="h4 mb-4 font-weight-bold">Change your password</h1>
                                <p>Use the form below to change your password.</p>

                                {% if form.errors %}
                                <div class="alert alert-primary" role="alert">
                                    Error: Please try again!
                                </div>
                                {% endif %}

                                <label class="small font-weight-bold">{{ form.new_password1.label}}</label>
                                {{ form.new_password1 }}
                                <label class="small font-weight-bold">{{ form.new_password2.label}}</label>
                                {{ form.new_password2 }}
                                <ul>
                                    <li>Your password can’t be too similar to your other personal information.</li>
                                    <li>Your password must contain at least 8 characters.</li>
                                    <li>Your password can’t be a commonly used password.</li>
                                    <li>Your password can’t be entirely numeric.</li>
                                </ul>
                                <button class="btn btn-primary btn-block py-2 mb-4 mt-5 font-weight-bold" type="submit"
                                    value="Change">Submit
                                </button>
                            </form>

                            <p class="small text-center pt-4">
                                <a href="{% url "account:login" %}">Already have an account?</a>
                            </p>
                            <p class="small text-center">
                                <a href="{% url "account:register" %}">Help Center?</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6 d-none d-md-flex bg-image"></div>
    </div>
</div>
{% endblock %}

account/templates/user/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'account:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

account/templates/user/password_reset_form.html
{% extends "base.html" %}
{% block title %}Log-in{% endblock %}
{% block content %}

{% if request.user.is_authenticated %}
    <script>
        window.location.href = '{% url "account:dashboard" %}';
    </script>
{% endif %}

<style>
    .account-form input {
        border: 2px solid #ccc;
        height: calc(2em + .75rem + 2px);
    }

    .account-form input:focus {
        border-color: #1497ff;
        box-shadow: inset 0 0px 0px rgba(0, 0, 0, 0.075), 0 0 0px rgba(255, 0, 0, 0.6);
    }
</style>

<div class="container-fluid">
    <div class="row no-gutter">
        <div class="col-md-12">
            <div class="login d-flex align-items-center py-5">
                <div class="container">
                    <div class="row">
                        <div class="col-12 col-md-12 mx-auto">
                            <form class="account-form p-4 rounded col-lg-8 mx-auto" method="post" action="{% url 'account:pwdreset' %}">
                                <p class="h3 mb-4 font-weight-bold">Forgotten your password?</p>
                                    <p>Enter your e-mail address to obtain a new password.</p>
                                    {% if form.errors %}
                                        <div class="alert alert-primary" role="alert">
                                            Error: Please try again!
                                        </div>
                                    {% endif %}
                                    {% csrf_token %}
                                    <label class="small font-weight-bold">{{ form.email.label}}</label>
                                    {{ form.email }}
                                    <button class="btn btn-primary btn-block py-2 mb-4 mt-5 fw-bold w-100" type="submit"value="Send e-mail">Send e-mail</button>
                                    <p class="text-center"><a href="{% url "account:login" %}">Login</a></p>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

account/templates/user/reset_status.html
{% extends "base.html" %}
{% block title %}Log-in{% endblock %}
{% block content %}

<style>
    .container-fluid {
        max-width: 100%;
    }

    .account-form input {
        border: 2px solid #ccc;
        height: calc(2em + .75rem + 2px);
    }

    .account-form input:focus {
        border-color: #1497ff;
        box-shadow: none;
    }
</style>


<div class="container-fluid">
    <div class="row no-gutter">
        <div class="col-md-12">
            <div class="login d-flex align-items-center py-5">
                <div class="container">
                    <div class="row">
                        <div class="col-12 col-lg-6  mx-auto">
                            <div class="p-4">
                                {% if 'email' in request.get_full_path %}
                                        <h3 class="mb-4">Password Reset Success</h3>
                                        <p>Check your email for instructions</p>
                                {% endif%}
                                {% if 'complete' in request.get_full_path %}
                                        <h3 class="mb-4">Password Reset Success</h3>
                                        <a href="{% url "account:login" %}">Login</a>
                                {% endif%}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}