basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'

urlpatterns = [
   path('', views.basket_summary, name='basket_summary'),
   path('add/', views.basket_add, name='basket_add'),
   path('delete/', views.basket_delete, name='basket_delete'),
   path('update/', views.basket_update, name='basket_update'),
]

core/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('orders/', include('order.urls', namespace='orders')),
    path('__debug__', include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

basket/models.py
from django.db import models  # noqa

# Create your models here.

basket/views.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render

from store.models import Product

from .basket import Basket


def basket_summary(request):
    basket = Basket(request)
    return render(request, 'summary.html', {'basket': basket})


def basket_add(request):
    basket = Basket(request)

    # get data from ajax request
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        product = get_object_or_404(Product, id=product_id)
        basket.add(product=product, product_qty=product_qty)

        basketqty = basket.__len__()
        response = JsonResponse({'qty': basketqty})
        return response


def basket_delete(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        basket.delete(product=product_id)
        basketqty = basket.__len__()
        baskettotal = basket.get_total_price()

        response = JsonResponse({'qty': basketqty, 'subtotal': baskettotal})
        return response


def basket_update(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        basket.update(product=product_id, product_qty=product_qty)

        basketqty = basket.__len__()
        baskettotal = basket.get_total_price()

        response = JsonResponse({'qty': basketqty, 'subtotal': baskettotal})
        return response

basket/templates/summary.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Basket Summary{% endblock %}
{% block content %}

    <main class="pt-5">
        <div class="container">
            <h1 class="h5">Shopping basket</h1>
            {% for item in basket %}
                {% with product=item.product %}
                    <div data-index="{{ product.id }}" class="row mb-4 border product-item">
                        <div class="col-md-3 col-lg-2 order-md-first bg-light">
                            {% for image in product.product_image.all %}
                            {% if image.is_feature  %}
                            <img class="img-fluid mx-auto d-block" width="120px" alt="{{ image.image.alt_text }}"
                                 src="{{ image.image.url }}">
                            {% endif %}
                        {% endfor %}
                        </div>
                        <div class="col-md-9 col-lg-10 ps-md-3 ps-lg-10">
                            <a href="{{ product.get_absolute_url }}" class="text-decoration-none text-reset">
                                <h1 class="h5 pt-2">{{ product.title }}</h1>
                            </a>
                            <div class="border">
                                <div class="col border-bottom">
                                    <div class="row p-3">
                                        <div class="col-6">Hardback Book</div>
                                        <div class="">Sub Total: <span class="fw-bold">£</span>
                                            <div id="subtotal"
                                                 class="d-inline-flex fw-bold">{{ basket.get_subtotal_price }}</div>
                                        </div>
                                        <div id="">Shipping <span class="small">(Next day delivery)</span>: <span
                                                class="fw-bold">£11.50</span></div>
                                        <div class="pt-2">Total to pay: <span class="fw-bold h5">£</span><span
                                                id="total" class="fw-bold h5">{{ basket.get_total_price }}</span></div>
                                    </div>
                                </div>
                            </div>
                            <div class="col">
                                <div class="row p-3">
                                    <div class="col-12">
                                        <label for="select">Qty</label>
                                        <select id="select{{ product.id }}">
                                            <option selected>
                                                {{ item.qty }}
                                            </option>
                                            <option value="">1</option>
                                            <option value="">2</option>
                                            <option value="">3</option>
                                            <option value="">4</option>
                                        </select>
                                        <button type="button" id="update-button" data-index="{{ product.id }}"
                                                class="btn btn-outline-secondary btn-sm update-button">
                                            Update
                                        </button>
                                        <button type="button" id="delete-button" data-index="{{ product.id }}"
                                                class="btn btn-outline-secondary btn-sm delete-button">
                                            Delete
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    </div>
                {% endwith %}
            {% endfor %}
        <div class="col-12 text-end">
            <div class="h6 fw-bold">Sub Total: R$
                <div id="subtotal" class="d-inline-flex">{{ basket.get_total_price }}</div>
            </div>
            <a role="button" href="{% url 'payment:basket' %}" class="btn btn-success fw-bold"
               type="submit">Checkout</a>
        </div>
        </div>
    </main>

    <!--Start Cart Script -->


    <script>

        // Delete Item
        $(document).on('click', '#delete-button', function (e) {
            e.preventDefault();
            var self = this
            var prodid = $(self).data('index');
            $.ajax({
                type: 'POST',
                url: '{% url "basket:basket_delete" %}',
                data: {
                    productid: $(self).data('index'),
                    csrfmiddlewaretoken: '{{ csrf_token }}',
                    action: 'post'
                },
                success: function (json) {
                    $('.product-item[data-index="' + prodid + '"]').remove();
                    document.getElementById("basket-qty").innerHTML = json.qty
                    document.getElementById("subtotal").innerHTML = json.subtotal
                },
                error: function (xhr, errmsg, err) {
                }

            });
        })


        // Update Item
        $(document).on('click', '#update-button', function (e) {
            e.preventDefault();
            var self = this
            var prodid = $(self).data('index');
            $.ajax({
                type: 'POST',
                url: '{% url "basket:basket_update" %}',
                data: {
                    productid: $(self).data('index'),
                    productqty: $('#select' + prodid + ' option:selected').text(),
                    csrfmiddlewaretoken: '{{ csrf_token }}',
                    action: 'post'
                },
                success: function (json) {
                    document.getElementById("basket-qty").innerHTML = json.qty
                    document.getElementById("subtotal").innerHTML = json.subtotal
                },
                error: function (xhr, errmsg, err) {
                }

            });
        })
    </script>
    <!--END Cart Script -->


{% endblock content %}