account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .forms import PwdResetConfirmForm, PwdResetForm, UserLoginForm

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html',
                                                form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/account/login/'), name='logout'),
    path('register/', views.account_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>', views.account_activate, name='activate'),
    # Reset password
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="user/password_reset_form.html",
                                                                 success_url='password_reset_email_confirm',
                                                                 email_template_name='user/password_reset_email.html',
                                                                 form_class=PwdResetForm), name='pwdreset'),
    path('password_reset_confirm/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(template_name='user/password_reset_confirm.html',
                                                     success_url='/account/password_reset_complete/',
                                                     form_class=PwdResetConfirmForm),
         name="password_reset_confirm"),
    path('password_reset/password_reset_email_confirm/',
         TemplateView.as_view(template_name="user/reset_status.html"), name='password_reset_done'),
    path('password_reset_complete/',
         TemplateView.as_view(template_name="user/reset_status.html"), name='password_reset_complete'),
    # User dashboard
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/edit/', views.edit_details, name='edit_details'),
    path('profile/delete-user/', views.delete_user, name='delete_user'),
    path('profile/delete-confirm/', TemplateView.as_view(template_name='user/delete_confirm.html'),
         name='delete_confirmation'),
    path('addresses/', views.view_address, name='addresses'),
    path('add-address/', views.add_address, name='add_address'),
    path('addresses/edit/<slug:id>/', views.edit_address, name='edit_address'),
    path('addresses/delete/<slug:id>/', views.delete_address, name='delete_address'),
    path('addresses/set-default/<slug:id>/', views.set_default, name='set_default'),
    # Wish list
    path('wishlist/', views.wishlist, name='wishlist'),
    path('withlist/add-to-wishlist/<int:id>/', views.add_to_wishlist, name="add_to_wishlist"),
]

core/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('orders/', include('order.urls', namespace='orders')),
    path('__debug__', include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

account/forms.py
from django import forms
from django.contrib.auth.forms import (AuthenticationForm, PasswordResetForm,
                                       SetPasswordForm)

from .models import Address, Customer


class UserAddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ["full_name", "phone_number", "address_line_1", "address_line_2", "town_city", "postcode"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["full_name"].widget.attrs.update(
            {"class": "form-control mb-2 account-form", "placeholder": "Full Name"}
        )
        self.fields["phone_number"].widget.attrs.update(
            {"class": "form-control mb-2 account-form", "placeholder": "phone number"}
        )
        self.fields["address_line_1"].widget.attrs.update(
            {"class": "form-control mb-2 account-form", "placeholder": "Address line 1"}
        )
        self.fields["address_line_2"].widget.attrs.update(
            {"class": "form-control mb-2 account-form", "placeholder": "Address line 2"}
        )
        self.fields["town_city"].widget.attrs.update(
            {"class": "form-control mb-2 account-form", "placeholder": "Town city"}
        )
        self.fields["postcode"].widget.attrs.update(
            {"class": "form-control mb-2 account-form", "placeholder": "Post Code"}
        )


class UserLoginForm(AuthenticationForm):

    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control mb-3', 'placeholder': 'Username', 'id': 'login-username'}))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Password',
            'id': 'login-pwd',
        }
    ))


class RegistrationForm(forms.ModelForm):
    user_name = forms.CharField(label='Enter Username', min_length=4, max_length=50, help_text='Required')
    email = forms.EmailField(max_length=100, help_text='Required',
                             error_messages={'required': 'Sorry, you will need an email'})
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = Customer
        fields = ('user_name', 'email',)

    def clean_username(self):
        user_name = self.cleaned_data['user_name'].lower()
        r = Customer.objects.filter(user_name=user_name)
        if r.count():
            raise forms.ValidationError('Username already exists')
        return user_name

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords do not match.')
        return cd['password2']

    def clean_email(self):
        email = self.cleaned_data['email']
        if Customer.objects.filter(email=email).exists():
            raise forms.ValidationError(
                'Please use another email, that is already taken')
        return email

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user_name'].widget.attrs.update({'class': 'form-control mb-3', 'placeholder': 'Username'})
        self.fields['email'].widget.attrs.update({'class': 'form-control mb-3', 'placeholder': 'Email'})
        self.fields['password'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'Password', 'name': 'email'})
        self.fields['password2'].widget.attrs.update({'class': 'form-control mb-3', 'placeholder': 'Repeat Password'})


class PwdResetForm(PasswordResetForm):

    email = forms.EmailField(max_length=254, widget=forms.TextInput(
        attrs={'class': 'form-control mb-3', 'placeholder': 'Email', 'id': 'form-email'}))

    def clean_email(self):
        email = self.cleaned_data['email']
        u = Customer.objects.filter(email=email)
        if not u:
            raise forms.ValidationError(
                'Unfortunatley we can not find that email address')
        return email


class PwdResetConfirmForm(SetPasswordForm):
    new_password1 = forms.CharField(
        label='New password', widget=forms.PasswordInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'New Password', 'id': 'form-newpass'}))
    new_password2 = forms.CharField(
        label='Repeat password', widget=forms.PasswordInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'New Password', 'id': 'form-new-pass2'}))


class UserEditForm(forms.ModelForm):

    email = forms.EmailField(
        label='Account email (can not be changed)', max_length=200, widget=forms.TextInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'email', 'id': 'form-email', 'readonly': 'readonly'}))

    user_name = forms.CharField(
        label='Firstname', min_length=4, max_length=50, widget=forms.TextInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'Username',
                   'id': 'form-firstname', 'readonly': 'readonly'}))

    first_name = forms.CharField(
        label='Username', min_length=4, max_length=50, widget=forms.TextInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'Firstname', 'id': 'form-lastname'}))

    class Meta:
        model = Customer
        fields = ('email', 'user_name', 'first_name',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user_name'].required = True
        self.fields['email'].required = True

account/views.py
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode

from order.views import user_orders
from store.models import Product

from .forms import RegistrationForm, UserAddressForm, UserEditForm
from .models import Address, Customer
from .token import account_activation_token


@login_required
def wishlist(request):
    products = Product.objects.filter(users_wishlist=request.user.id)
    return render(request, 'dashboard/user_wish_list.html', {'wishlist': products})


@login_required
def add_to_wishlist(request, id):
    product = get_object_or_404(Product, pk=id)
    if product.users_wishlist.filter(id=request.user.id).exists():
        product.users_wishlist.remove(request.user)
        messages.success(request, product.title + " has been removed from your WishList.")
    else:
        product.users_wishlist.add(request.user)
        messages.success(request, "Added " + product.title + " to your WishList.")
    return HttpResponseRedirect(request.META["HTTP_REFERER"])


@login_required
def dashboard(request):
    orders = user_orders(request)
    return render(request, 'dashboard/dashboard.html', {'orders': orders})


@login_required
def edit_details(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.POST)

        if user_form.is_valid():
            user_form.save()
    else:
        user_form = UserEditForm(instance=request.user)

    return render(request, 'user/edit_details.html', {'user_form': user_form})


@login_required
def delete_user(request):
    user = Customer.objects.get(user_name=request.user)
    user.is_active = False
    user.save()
    logout(request)
    return redirect('account:delete_confirmation')


def account_register(request):
    if request.user.is_authenticated:
        return redirect('/')

    if request.method == 'POST':
        registerForm = RegistrationForm(request.POST)
        if registerForm.is_valid():
            user = registerForm.save(commit=False)
            cd = registerForm.cleaned_data
            user.email = cd['email']
            user.set_password(cd['password'])
            user.is_active = False
            user.save()
            # Setup email
            current_site = get_current_site(request)
            subject = 'Activate your Account'
            message = render_to_string('registration/account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            user.email_user(subject=subject, message=message)
            return HttpResponse('registered succesfully and activation sent')
    else:
        registerForm = RegistrationForm()
    return render(request, 'registration/register.html', {'form': registerForm})


def account_activate(request, uidb64, token):
    user = None
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = Customer.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, user.DoesNotExist):
        pass

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        return redirect('account:dashboard')
    else:
        return render(request, 'registration/activation_invalid.html')


# Addresses

@login_required
def view_address(request):
    addresses = Address.objects.filter(customer=request.user)
    return render(request, 'dashboard/addresses.html', {'addresses': addresses})


@login_required
def add_address(request):
    if request.method == 'POST':
        form = UserAddressForm(data=request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.customer = request.user
            form.save()
            return HttpResponseRedirect(reverse('account:addresses'))
    else:
        form = UserAddressForm()
    return render(request, 'dashboard/edit_addresses.html', {"form": form})


@login_required
def edit_address(request, id):
    if request.method == 'POST':
        address = Address.objects.get(pk=id, customer=request.user)
        form = UserAddressForm(data=request.POST, instance=address)
        if form.is_valid():
            form.save()
            HttpResponseRedirect(reverse('account:addresses'))
    else:
        address = Address.objects.get(pk=id, customer=request.user)
        form = UserAddressForm(instance=address)
    return render(request, 'dashboard/edit_addresses.html', {"form": form})


@login_required
def delete_address(request, id):
    address = Address.objects.get(pk=id, customer=request.user)
    address.delete()
    return redirect(reverse("account:addresses"))


@login_required
def set_default(request, id):
    """ set default address """
    Address.objects.filter(customer=request.user, default=True).update(default=False)
    Address.objects.filter(pk=id, customer=request.user).update(default=True)
    return redirect("account:addresses")

account/templates/dashboard/addresses.html
{% extends 'base.html' %}
{% block title %} Edit Addresses {% endblock title %}

{% block content %}
    <main class="pt-5">
        <div class="container" style="max-width: 1000px">
            <h1 class="h2">Your Addresses</h1>
            <div>Manage your <b>addresses</b> and delivery preferences</div>
            <hr/>

            <div class="container px-0">
                <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                    <div class="col">
                        <a href="{% url "account:add_address" %}" class="text-reset text-decoration-none" role="button"
                           style="max-width: 540px;">
                            <div class="card mb-3 h-100" style="border: dashed 2px #ccc;">
                                <div class="row g-0 h-100">
                                    <div class="col-12" style="min-height:100px">
                                        <div class="card-body text-center position-absolute top-50 start-50 translate-middle">
                                            <svg style="color:#ccc;" xmlns="http://www.w3.org/2000/svg" width="60"
                                                 height="60"
                                                 fill="currentColor"
                                                 class="bi bi-plus" viewBox="0 0 16 16">
                                                <path
                                                        d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
                                            </svg>
                                            <h1 class="h5">Add Address</h1>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                    {% for address in addresses %}
                        <div class="col">
                            <div class="card pb-3">
                                <div class="card-header bg-white small text-muted">
                                    {% if address.default %}
                                        Default
                                    {% endif %}
                                    &nbsp;
                                </div>
                                <div class="card-body small pb-1">
                                    <p class="card-text m-0 fw-bold">{{ address.full_name }}</p>
                                    <p class="card-text m-0">{{ address.address_line_1 }}</p>
                                    <p class="card-text m-0">{{ address.address_line_2 }}</p>
                                    <p class="card-text m-0">{{ address.town_city }}</p>
                                    <p class="card-text m-0">{{ address.postcode }}</p>
                                    <p class="card-text m-0">Phone number: {{ address.phone_number }}</p>
                                    <div class="pt-5">
                                        <a href="{% url 'account:edit_address' address.id %}"
                                           class="text-decoration-none">Edit</a>
                                        |
                                        <a href="{% url 'account:delete_address' address.id %}"
                                           class="text-decoration-none">Delete</a>
                                        {% if not address.default %}
                                            |<a href="{% url 'account:set_default' address.id %}"
                                                class="text-decoration-none">Set Default</a>

                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                            </a>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </main>
{% endblock content %}

account/templates/dashboard/dashboard.html
{% extends "base.html" %}
{% load static %}
{% block title %}Basket Summary{% endblock %}

{% block content %}
    <main class="pt-5">
        <div class="container" style="max-width: 1000px">
            <div class="col-12">
                <h1 class="h2">Your Dashboard</h1>
            </div>
            <div class="col-12 d-flex justify-content-between">
                <div>Manage your <b>orders</b> and personal details</div>
                <div><a href="{% url "account:edit_details" %}">Change Details</a></div>
            </div>
            <hr/>
        </div>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 mx-auto" style="max-width: 1000px">
            <div class="col">
                <a href="#" class="text-reset text-decoration-none" role="button" style="max-width: 540px;">
                    <div class="card mb-3">
                        <div class="row g-0">
                            <div class="col-2 position-relative">
                                <svg class="position-absolute top-50 start-50 translate-middle"
                                     xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor"
                                     class="bi bi-gift"
                                     viewBox="0 0 16 16">
                                    <path
                                            d="M3 2.5a2.5 2.5 0 0 1 5 0 2.5 2.5 0 0 1 5 0v.006c0 .07 0 .27-.038.494H15a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1v7.5a1.5 1.5 0 0 1-1.5 1.5h-11A1.5 1.5 0 0 1 1 14.5V7a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h2.038A2.968 2.968 0 0 1 3 2.506V2.5zm1.068.5H7v-.5a1.5 1.5 0 1 0-3 0c0 .085.002.274.045.43a.522.522 0 0 0 .023.07zM9 3h2.932a.56.56 0 0 0 .023-.07c.043-.156.045-.345.045-.43a1.5 1.5 0 0 0-3 0V3zM1 4v2h6V4H1zm8 0v2h6V4H9zm5 3H9v8h4.5a.5.5 0 0 0 .5-.5V7zm-7 8V7H2v7.5a.5.5 0 0 0 .5.5H7z"/>
                                </svg>
                            </div>
                            <div class="col-10">
                                <div class="card-body ps-0 ps-md-1">
                                    <h1 class="h5">Orders</h1>
                                    <p class="card-text small text-muted">View, Track, Change or buy again</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col">
                <a href="{% url "account:edit_details" %}" class="text-reset text-decoration-none" role="button"
                   style="max-width: 540px;">
                    <div class="card mb-3">
                        <div class="row g-0">
                            <div class="col-2 position-relative">
                                <svg class="position-absolute top-50 start-50 translate-middle"
                                     xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor"
                                     class="bi bi-shield-lock" viewBox="0 0 16 16">
                                    <path d="M5.338 1.59a61.44 61.44 0 0 0-2.837.856.481.481 0 0 0-.328.39c-.554 4.157.726 7.19 2.253 9.188a10.725 10.725 0 0 0 2.287 2.233c.346.244.652.42.893.533.12.057.218.095.293.118a.55.55 0 0 0 .101.025.615.615 0 0 0 .1-.025c.076-.023.174-.061.294-.118.24-.113.547-.29.893-.533a10.726 10.726 0 0 0 2.287-2.233c1.527-1.997 2.807-5.031 2.253-9.188a.48.48 0 0 0-.328-.39c-.651-.213-1.75-.56-2.837-.855C9.552 1.29 8.531 1.067 8 1.067c-.53 0-1.552.223-2.662.524zM5.072.56C6.157.265 7.31 0 8 0s1.843.265 2.928.56c1.11.3 2.229.655 2.887.87a1.54 1.54 0 0 1 1.044 1.262c.596 4.477-.787 7.795-2.465 9.99a11.775 11.775 0 0 1-2.517 2.453 7.159 7.159 0 0 1-1.048.625c-.28.132-.581.24-.829.24s-.548-.108-.829-.24a7.158 7.158 0 0 1-1.048-.625 11.777 11.777 0 0 1-2.517-2.453C1.928 10.487.545 7.169 1.141 2.692A1.54 1.54 0 0 1 2.185 1.43 62.456 62.456 0 0 1 5.072.56z"/>
                                    <path d="M9.5 6.5a1.5 1.5 0 0 1-1 1.415l.385 1.99a.5.5 0 0 1-.491.595h-.788a.5.5 0 0 1-.49-.595l.384-1.99a1.5 1.5 0 1 1 2-1.415z"/>
                                </svg>
                            </div>
                            <div class="col-10">
                                <div class="card-body ps-0 ps-md-1">
                                    <h1 class="h5">Login & Security</h1>
                                    <p class="card-text small text-muted">Edit login, email and phone number</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col">
                <a href="{% url "account:addresses" %}" class="text-reset text-decoration-none" role="button"
                   style="max-width: 540px;">
                    <div class="card mb-3">
                        <div class="row g-0">
                            <div class="col-2 position-relative">
                                <svg class="position-absolute top-50 start-50 translate-middle"
                                     xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor"
                                     class="bi bi-truck" viewBox="0 0 16 16">
                                    <path d="M0 3.5A1.5 1.5 0 0 1 1.5 2h9A1.5 1.5 0 0 1 12 3.5V5h1.02a1.5 1.5 0 0 1 1.17.563l1.481 1.85a1.5 1.5 0 0 1 .329.938V10.5a1.5 1.5 0 0 1-1.5 1.5H14a2 2 0 1 1-4 0H5a2 2 0 1 1-3.998-.085A1.5 1.5 0 0 1 0 10.5v-7zm1.294 7.456A1.999 1.999 0 0 1 4.732 11h5.536a2.01 2.01 0 0 1 .732-.732V3.5a.5.5 0 0 0-.5-.5h-9a.5.5 0 0 0-.5.5v7a.5.5 0 0 0 .294.456zM12 10a2 2 0 0 1 1.732 1h.768a.5.5 0 0 0 .5-.5V8.35a.5.5 0 0 0-.11-.312l-1.48-1.85A.5.5 0 0 0 13.02 6H12v4zm-9 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm9 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"/>
                                </svg>
                            </div>
                            <div class="col-10">
                                <div class="card-body ps-0 ps-md-1">
                                    <h1 class="h5">Your Addresses</h1>
                                    <p class="card-text small text-muted">Edit your shipping addresses</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col">
                <a href="{% url "account:wishlist" %}" class="text-reset text-decoration-none" role="button"
                   style="max-width: 540px;">
                    <div class="card mb-3">
                        <div class="row g-0">
                            <div class="col-2 position-relative">
                                <svg class="position-absolute top-50 start-50 translate-middle"
                                     xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor"
                                     class="bi bi-shield-lock" viewBox="0 0 16 16">
                                    <path d="M14.5 3a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2z"/>
                                    <path d="M7 5.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5m-1.496-.854a.5.5 0 0 1 0 .708l-1.5 1.5a.5.5 0 0 1-.708 0l-.5-.5a.5.5 0 1 1 .708-.708l.146.147 1.146-1.147a.5.5 0 0 1 .708 0M7 9.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5m-1.496-.854a.5.5 0 0 1 0 .708l-1.5 1.5a.5.5 0 0 1-.708 0l-.5-.5a.5.5 0 0 1 .708-.708l.146.147 1.146-1.147a.5.5 0 0 1 .708 0"/>
                                </svg>
                            </div>
                            <div class="col-10">
                                <div class="card-body ps-0 ps-md-1">
                                    <h1 class="h5">Your Wish List</h1>
                                    <p class="card-text small text-muted">View your wish list</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </a>
            </div>

            <div class="container" style="max-width: 1000px">
                {% for order in orders %}
                    <div class="row g-3">

                        <div class="col-12 bg-light p-3 d-flex justify-content-between">
                            <div class="d-flex d-flex-inline">

                                <div class="pe-3">{{ order.created }}</div>
                                <div class="dropdown">
                                    <a class="text-reset text-decoration-none dropdown-toggle" href="#" role="link"
                                       id="dropdownLink" data-bs-toggle="dropdown" aria-expanded="false">
                                        Dispacted to
                                        <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12"
                                             fill="currentColor" class="bi bi-chevron-down" viewBox="0 0 16 16">
                                            <path fill-rule="evenodd"
                                                  d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/>
                                        </svg>
                                    </a>

                                    <ul class="dropdown-menu" aria-labelledby="dropdownLink">
                                        <li class="item small">{{ order.full_name }}</li>
                                        <li class="item small">{{ order.address1 }}</li>
                                        <li class="item small">{{ order.address2 }}</li>
                                        <li class="item small">{{ order.post_code }}</li>
                                    </ul>
                                </div>

                            </div>
                            <div class="text-end">
                                Total paid: <span class="fw-bold">R${{ order.total_paid }}</span>
                            </div>
                        </div>
                        <div class="col-md-5 col-lg-4 order-md-last p-0 order-3">
                            <div class="d-grid gap-2 ">
                                <button class="btn btn-warning" type="button">Problem with order</button>
                                <button class="btn btn-light" type="button">Leave a review</button>
                            </div>
                        </div>

                        <div class="col-md-7 col-lg-8 p-0">

                            {% for item in order.items.all %}

                                <div class="card mb-3 border-0">
                                    <div class="row g-0">
                                        <div class="col-md-2 d-none d-md-block">
                                            <img class="img-fluid" style="width:90px"
                                                 src="{{ item.product.image.url }}"/>
                                        </div>
                                        <div class="col-md-10">
                                            <div class="card-body p-1">
                                                <a class="text-decoration-none"
                                                   href="{{ item.product.get_absolute_url }}">
                                                    <p class="card-text small">{{ item.product|title }}</p>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>


                            {% endfor %}


                        </div>

                    </div>
                {% endfor %}

            </div>
        </div>
    </main>





{% endblock %}